CREATE TABLE IF NOT EXISTS T_STA_PACOTE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    DESTINATION VARCHAR(255),
    DESCRIPTION TEXT,
    PRICE NUMERIC(10,2),
    DURATION VARCHAR(100),
    AVAILABLE_SEATS INTEGER,
    IMAGE_URL VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS T_STA_RESERVA (
    ID SERIAL PRIMARY KEY,
    PACKAGE_ID INTEGER REFERENCES T_STA_PACOTE(ID),
    PASSENGER_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    NUMBER_OF_PEOPLE INTEGER,
    TRAVEL_DATE VARCHAR(50),
    STATUS VARCHAR(50)
);